import React from 'react';
import { Icon, View } from 'native-base';
import Menu, { MenuItem } from 'react-native-material-menu';
import commonColor from './native-base-theme/variables/commonColor';
import PushNotification from 'react-native-push-notification'

export default class AppMenu extends React.Component {
    _menu = null;

    setMenuRef = ref => {
        this._menu = ref;
    };

    hideMenu = () => {
        this._menu.hide();
    };

    showMenu = () => {
        this._menu.show();
    };

    settingsPressed = () => {
        const { navigation: { navigate } } = this.props;

        this.hideMenu();

        PushNotification.localNotification({
            // Android Only Properties 
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            // ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_launcher", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            // bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "Reminder", // (optional) default: none
            // color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification
            priority: "high", // (optional) set notification priority, default: high
            visibility: "private", // (optional) set notification visibility, default: private
            importance: "high", // (optional) set notification importance, default: high
         
            // iOS and Android properties 
            title: "My Notification Title", // (optional)
            message: "My Notification Message", // (required)
            playSound: false, // (optional) default: true
            // soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
        }); 

        navigate('Settings')
    }

    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Menu
                    ref={this.setMenuRef}
                    button={<Icon style={{ padding: 10, color: commonColor.inverseTextColor }} onPress={this.showMenu} name="more" />}
                >
                    <MenuItem onPress={this.settingsPressed}>Settings</MenuItem>
                </Menu>
            </View>
        );
    }
}